name: "Github actions demo"
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: list directory
        run: ls -lh && docker version
