name: "Github actions demo"
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v2
      - name: list directory
        run: ls -lh
