name: "Github actions demo"
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: list directory
        run: docker version
